version: 0.0
os: linux
files:
  - source: /
    destination: /var/vmware/lightwave
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_wrapper.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server_wrapper.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  BeforeAllowTraffic:
    - location: scripts/before_allow_traffic.sh
      timeout: 300
      runas: root
